# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.50.5", auto_config: false, bridge: "VagrantSwitch"
  
  config.vm.box = "bento/centos-7"
  config.vm.box_version = "202012.28.0"
  config.vm.hostname = "activegate"
  config.vm.define "activegate"

  config.vm.provider "hyperv" do |h|
    h.memory = 4096
    h.maxmemory = 4096
    h.cpus = 2
    h.vmname = "activegate"

    h.enable_virtualization_extensions = true
    h.linked_clone = true

    h.vm_integration_services = {
      key_value_pair_exchange: true
    }
  end

  config.vm.provision "shell" do |s|
    s.path = "./scripts/configure_static_ip.sh"
  end

  config.vm.provision :reload

  config.vm.provision "shell" do |s|
    s.path = "./scripts/provision.sh"
  end

  config.vm.provision "shell" do |s|
    s.path = "./scripts/install_activegate.sh"
  end
end
